# Generated by Django 3.0.7 on 2020-06-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200625_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplatter',
            name='size',
            field=models.CharField(choices=[('Small', 'SM'), ('Large', 'LG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('Small', 'SM'), ('Large', 'LG')], max_length=5),
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('Small', 'SM'), ('Large', 'LG')], max_length=5),
        ),
    ]
