# Generated by Django 3.0.7 on 2020-07-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200626_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='large',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinnerplatter',
            name='small',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='large',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='small',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='large',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='small',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pasta',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='salad',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
